// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package backend

import (
	"context"
	"maxxgui/backend/handler"
	"maxxgui/backend/init_"
)

// Injectors from wire.go:

func NewApp() *App {
	context := ProvideContext()
	query := init_.InitQuery()
	crackHandler := &handler.CrackHandler{
		Ctx:   context,
		Query: query,
	}
	app := &App{
		ctx:          context,
		CrackHandler: crackHandler,
	}
	return app
}

// wire.go:

func ProvideContext() context.Context {
	return context.TODO()
}
