// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['handler']['CrackHandler']['Cancel'](arg1);
}

export function CancelAll() {
  return window['go']['handler']['CrackHandler']['CancelAll']();
}

export function GenerateReport(arg1, arg2) {
  return window['go']['handler']['CrackHandler']['GenerateReport'](arg1, arg2);
}

export function Scan(arg1) {
  return window['go']['handler']['CrackHandler']['Scan'](arg1);
}
