// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Cancel(arg1:string):Promise<boolean>;

export function CancelAll():Promise<boolean>;

export function GenerateReport(arg1:string,arg2:boolean):Promise<string>;

export function Scan(arg1:model.CrackTask):Promise<boolean>;
