// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Register(arg1:model.CrackTask,arg2:model.CrackResult):Promise<void>;
