// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Register(arg1, arg2) {
  return window['go']['model']['CrackProvider']['Register'](arg1, arg2);
}
