name: "Maxx-gui"
on:
  push:
    tags:
      - '*'

jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        go-version: [1.24.2]
        arch: [amd64, arm64]
        exclude:
          - platform: windows-latest
            arch: arm64
          - platform: ubuntu-latest
            arch: arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies on Linux
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libpcap-dev libwebkit2gtk-4.1-dev

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.1

      - name: Build Wails app on Ubuntu
        if: matrix.platform == 'ubuntu-latest' && matrix.arch == 'amd64'
        run: wails build -tags webkit2_41 -ldflags "-w -s" -trimpath -platform linux/amd64

      - name: Build Wails app on macOS
        if: matrix.platform == 'macos-latest'
        run: wails build -ldflags "-w -s" -trimpath -platform darwin/${{ matrix.arch }}

      - name: Build Wails app on Windows
        if: matrix.platform == 'windows-latest' && matrix.arch == 'amd64'
        run: wails build -ldflags "-w -s" -trimpath -platform windows/amd64

      - name: Upload Artifacts (Temporary)
        uses: actions/upload-artifact@v4
        with:
          name: maxxgui-${{ matrix.platform }}-${{ matrix.arch }}
          path: build/bin/*

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bin/*
          tag_name: ${{ github.ref_name }}
          name: "Maxx-GUI ${{ github.ref_name }}"
          body: "Pre-release build for ${{ github.ref_name }}. See [Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}